const userProfiles = [
  {
    username: "user1",
    name: "Danish Kamal",
    city: "Hyderabad",
    course: "MCA",
    work: "Frontend Developer",
    msgURL: "",
    linkedinURL: "https://www.linkedin.com/in/danishzayan",
    imageUrl:
      "https://avatars.githubusercontent.com/u/46997504?s=400&u=07c0ac700535b5afda53b66b6346ca7cdbc2bd6a&v=4",
    skills: [
      "UI / UX",
      "Front End Development",
      "HTML",
      "CSS",
      "JavaScript",
      "ReactJS",
      "Node",
    ],
  },
  {
    username: "user2",
    name: "Shadab Ansari",
    city: "Hyderabad",
    course: "MCA",
    work: "Frontend Developer",
    msgURL: "",
    linkedinURL: "https://www.linkedin.com/in/shadabdln",
    imageUrl:
      "https://avatars.githubusercontent.com/u/140787517?s=400&u=a263e252c9cc353a91c8f17b22deebdcecbe3713&v=4",
    skills: [
      "UI / UX",
      "Front End Development",
      "HTML",
      "CSS",
      "JavaScript",
      "ReactJS",
      "Node",
    ],
  },
  {
    username: "user3",
    name: "Shaquib Khan",
    city: "Hyderabad",
    course: "MCA",
    work: "Frontend Developer",
    msgURL: "",
    linkedinURL: "https://www.linkedin.com/in/shaquibkhan",
    imageUrl: "https://randomuser.me/api/portraits/men/1.jpg",
    skills: [
      "UI",
      "HTML",
      "CSS",
      "JavaScript",
      "ReactJS Learning",
      "DSA with Java",
    ],
  },
  {
    username: "user4",
    name: "Arnab Ghosh",
    city: "kolkata",
    course: "BCA",
    work: "React Developer",
    msgURL: "",
    linkedinURL: "https://www.linkedin.com/in/arnab-ghosh-7678b7282/",
    imageUrl: "https://avatars.githubusercontent.com/u/113178195?v=4",
    skills: [
      "FuLL Stack Web Developer",
      "ReactJS",
      "MongoDB",
      "NodeJS",
      "ExpressJS",
    ],
  },
  {
    username: "user5",
    name: "Gurnav Chaudhary",
    city: "Uttar Pradesh",
    course: "BCA",
    work: "Frontend Developer",
    msgURL: "",
    linkedinURL: "https://www.linkedin.com/in/gurnav-chaudhary-55310a1a1/",
    imageUrl: "https://avatars.githubusercontent.com/u/72142482?v=4",
    skills: ["UI", "HTML", "CSS", "JavaScript", "ReactJS Learning"],
  },

  {
    username: "user5",
    name: "Virej Dasani",
    city: "mumbai",
    course: "Computer Science",
    work: "YouTuber",
    msgURL: "",
    linkedinURL: "https://www.linkedin.com/in/virej-dasani-b64470209/",
    imageUrl: "https://avatars.githubusercontent.com/u/67495678?v=4",
    skills: ["Unity", "ReactJS", "JavaScript", "NodeJS", "Python"],
  },
  {
    username: "user7",
    name: "Tanya Gupta",
    city: "Chandigarh",
    course: "Btech-cse",
    work: "Fullstack Developer",
    msgURL: "",
    linkedinURL: "https://www.linkedin.com/in/tanya-gupta-875b13228/",
    imageUrl: "https://randomuser.me/api/portraits/women/56.jpg",
    skills: [
      "UI / UX",
      "Front End Development",
      "HTML",
      "CSS",
      "JavaScript",
      "ReactJS",
      "Node",
      "MongoDB",
      "Express",
      "Flask",
      "Firebase",
      "Digital Ocean",
      "Docker",
    ],
  },

{
    username: "user8",
    name: "Sree Vyshnavi",
    city: "",
    course: "BTech",
    work: "Fullstack Developer",
    msgURL: "sreevysh2002@gmail.com",
    linkedinURL: "https://www.linkedin.com/in/sree-vyshnavi/",
    imageUrl: "https://freesvg.org/img/1519402404.png",
    skills: [
      "Python",
      "C++",
      "MySQL",
      "PHP",
      "HTML5",
      "CSS3",
      "JavaScript",
      "NodeJS",
      "ReactJS",
    ],
  },

    {
      username: "user9",
      name: "Sanika Kadam",
      city: "Mumbai",
      course: "BSC-IT",
      work: "Frotend Developer",
      msgURL: "",
      linkedinURL: "https://www.linkedin.com/in/sanika-kadam-a4600b22b/",
      imageUrl: "https://avatars.githubusercontent.com/u/96229011?v=4",
      skills: [
        "UI / UX",
        "Front End Development",
        "HTML",
        "CSS",
        "JavaScript",
        "ReactJS",
        "Node",
        "MongoDB",
      ],
    },

  {
    username: "user10",
    name: "Harash Parihar",
    city: "Jammu",
    course: "MCA",
    work: "Web3 Developer",
    msgURL: "",
    linkedinURL: "https://www.linkedin.com/in/harash-parihar-874785225",
    imageUrl: "https://avatars.githubusercontent.com/u/73985710?v=4",
    skills: [
      "Front End Development",
      "HTML",
      "CSS",
      "JavaScript",
      "ReactJS",
      "React-Native",
      "NextJs",
      "Python",
      "C++",
      "Solidity",
      "Rust",
    ],
  },
  {
    username: "user11",
    name: "Reajul Haque",
    city: "Dhaka",
    course: "MCA",
    work: "Backend Developer",
    msgURL: "",
    linkedinURL: "https://www.linkedin.com/in/reayz",
    imageUrl: "https://avatars.githubusercontent.com/u/21260946?v=4",
    skills: [
      "Back End Development",
      "C#",
      ".Net",
      "EF",
      "Dapper",
      "MS SQL",
    ],
  },
  {
    username: "user11",
    name: "Vinay Sharma",
    city: "Mumbai",
    course: "BSC-IT",
    work: "Frotend Developer",
    msgURL: "",
    linkedinURL: "https://www.linkedin.com/in/vinay-sharma-a76357261/",
    imageUrl: "https://avatars.githubusercontent.com/u/120549574?s=400&u=7c56b0e54efd9a0fa9df8014cc45b26d553aaa93&v=4",
    skills: [
      "Front End Development",
      "HTML",
      "CSS",
      "JavaScript",
      "ReactJS",
      "MYSQL", 
      "Python",
    ],
  },
  {
    username: "user13",
    name: "Shafaque Jamal Ansari",
    city: "Lucknow",
    course: "Btech",
    work: "Frontend Developer",
    msgURL: "",
    linkedinURL: "https://www.linkedin.com/in/shafaque-jamal-114743257?trk=contact-info",
    imageUrl:
      "https://avatars.githubusercontent.com/u/146312677?v=4",
    skills: [
      "Front End Development",
      "HTML",
      "CSS",
      "JavaScript",
      "C",
      "C++",
      "Node",
      "ReactJS",
    ],
  },

]

  // Add your Data order wise


export default userProfiles;
