const userProfiles = [
  {
    username: "user1",
    name: "Danish Kamal",
    city: "Hyderabad",
    course: "MCA",
    work: "Frontend Developer",
    msgURL: "",
    linkedinURL: "https://www.linkedin.com/in/danishzayan",
    imageUrl:
      "https://avatars.githubusercontent.com/u/46997504?s=400&u=07c0ac700535b5afda53b66b6346ca7cdbc2bd6a&v=4",
    skills: [
      "UI / UX",
      "Front End Development",
      "HTML",
      "CSS",
      "JavaScript",
      "ReactJS",
      "Node",
    ],
  },
  {
    username: "user2",
    name: "Shadab Ansari",
    city: "Hyderabad",
    course: "MCA",
    work: "Frontend Developer",
    msgURL: "",
    linkedinURL: "https://www.linkedin.com/in/shadabdln",
    imageUrl:
      "https://avatars.githubusercontent.com/u/140787517?s=400&u=a263e252c9cc353a91c8f17b22deebdcecbe3713&v=4",
    skills: [
      "UI / UX",
      "Front End Development",
      "HTML",
      "CSS",
      "JavaScript",
      "ReactJS",
      "Node",
    ],
  },
  {
    username: "user3",
    name: "Shaquib Khan",
    city: "Hyderabad",
    course: "MCA",
    work: "Frontend Developer",
    msgURL: "",
    linkedinURL: "https://www.linkedin.com/in/shaquibkhan",
    imageUrl: "https://randomuser.me/api/portraits/men/1.jpg",
    skills: [
      "UI",
      "HTML",
      "CSS",
      "JavaScript",
      "ReactJS Learning",
      "DSA with Java",
    ],
  },
  {
    username: "user4",
    name: "Arnab Ghosh",
    city: "kolkata",
    course: "BCA",
    work: "React Developer",
    msgURL: "",
    linkedinURL: "https://www.linkedin.com/in/arnab-ghosh-7678b7282/",
    imageUrl: "https://avatars.githubusercontent.com/u/113178195?v=4",
    skills: [
      "FuLL Stack Web Developer",
      "ReactJS",
      "MongoDB",
      "NodeJS",
      "ExpressJS",
    ],
  },
  {
    username: "user5",
    name: "Gurnav Chaudhary",
    city: "Uttar Pradesh",
    course: "BCA",
    work: "Frontend Developer",
    msgURL: "",
    linkedinURL: "https://www.linkedin.com/in/gurnav-chaudhary-55310a1a1/",
    imageUrl: "https://avatars.githubusercontent.com/u/72142482?v=4",
    skills: ["UI", "HTML", "CSS", "JavaScript", "ReactJS Learning"],
  },

  {
    username: "user5",
    name: "Virej Dasani",
    city: "mumbai",
    course: "Computer Science",
    work: "YouTuber",
    msgURL: "",
    linkedinURL: "https://www.linkedin.com/in/virej-dasani-b64470209/",
    imageUrl: "https://avatars.githubusercontent.com/u/67495678?v=4",
    skills: ["Unity", "ReactJS", "JavaScript", "NodeJS", "Python"],
  },
  {
    username: "user7",
    name: "Tanya Gupta",
    city: "Chandigarh",
    course: "Btech-cse",
    work: "Fullstack Developer",
    msgURL: "",
    linkedinURL: "https://www.linkedin.com/in/tanya-gupta-875b13228/",
    imageUrl: "https://randomuser.me/api/portraits/women/56.jpg",
    skills: [
      "UI / UX",
      "Front End Development",
      "HTML",
      "CSS",
      "JavaScript",
      "ReactJS",
      "Node",
      "MongoDB",
      "Express",
      "Flask",
      "Firebase",
      "Digital Ocean",
      "Docker",
    ],
  },

  {
    username: "user8",
    name: "Sree Vyshnavi",
    city: "",
    course: "BTech",
    work: "Fullstack Developer",
    msgURL: "sreevysh2002@gmail.com",
    linkedinURL: "https://www.linkedin.com/in/sree-vyshnavi/",
    imageUrl: "https://freesvg.org/img/1519402404.png",
    skills: [
      "Python",
      "C++",
      "MySQL",
      "PHP",
      "HTML5",
      "CSS3",
      "JavaScript",
      "NodeJS",
      "ReactJS",
    ],
  },

  {
    username: "user9",
    name: "Sanika Kadam",
    city: "Mumbai",
    course: "BSC-IT",
    work: "Frotend Developer",
    msgURL: "",
    linkedinURL: "https://www.linkedin.com/in/sanika-kadam-a4600b22b/",
    imageUrl: "https://avatars.githubusercontent.com/u/96229011?v=4",
    skills: [
      "UI / UX",
      "Front End Development",
      "HTML",
      "CSS",
      "JavaScript",
      "ReactJS",
      "Node",
      "MongoDB",
    ],
  },

  {
    username: "user10",
    name: "Harash Parihar",
    city: "Jammu",
    course: "MCA",
    work: "Web3 Developer",
    msgURL: "",
    linkedinURL: "https://www.linkedin.com/in/harash-parihar-874785225",
    imageUrl: "https://avatars.githubusercontent.com/u/73985710?v=4",
    skills: [
      "Front End Development",
      "HTML",
      "CSS",
      "JavaScript",
      "ReactJS",
      "React-Native",
      "NextJs",
      "Python",
      "C++",
      "Solidity",
      "Rust",
    ],
  },
  {
    username: "user11",
    name: "Reajul Haque Reayz",
    city: "Dhaka",
    course: "BSC",
    work: "Fullstack Developer",
    msgURL: "reayz77@yahoo.com",
    linkedinURL: "https://www.linkedin.com/in/reayz",
    imageUrl: "https://avatars.githubusercontent.com/u/21260946?v=4",
    skills: ["C#", ".Net", "Entity Framework", "Dapper", "MS SQL", "HTML", "CSS", "JS"],
  },
  {
    username: "user12",
    name: "Vinay Sharma",
    city: "Mumbai",
    course: "BSC-IT",
    work: "Frotend Developer",
    msgURL: "",
    linkedinURL: "https://www.linkedin.com/in/vinay-sharma-a76357261/",
    imageUrl:
      "https://avatars.githubusercontent.com/u/120549574?s=400&u=7c56b0e54efd9a0fa9df8014cc45b26d553aaa93&v=4",
    skills: [
      "Front End Development",
      "HTML",
      "CSS",
      "JavaScript",
      "ReactJS",
      "MYSQL",
      "Python",
    ],
  },
  {
    username: "user13",
    name: "Shafaque Jamal Ansari",
    city: "Lucknow",
    course: "Btech",
    work: "Frontend Developer",
    msgURL: "",
    linkedinURL:
      "https://www.linkedin.com/in/shafaque-jamal-114743257?trk=contact-info",
    imageUrl: "https://avatars.githubusercontent.com/u/146312677?v=4",
    skills: [
      "Front End Development",
      "HTML",
      "CSS",
      "JavaScript",
      "C",
      "C++",
      "Node",
      "ReactJS",
    ],
  },
  {
    username: "user14",
    name: "Narisara Limpisirisant",
    city: "Bangkok",
    course: "KMUTT-SIT",
    work: "Data Engineer",
    msgURL: "",
    linkedinURL: "https://www.linkedin.com/in/narisara01509/",
    imageUrl:
      "https://scontent.fbkk5-3.fna.fbcdn.net/v/t39.30808-6/346975611_761965482251979_2698396315890320504_n.jpg?_nc_cat=111&ccb=1-7&_nc_sid=a2f6c7&_nc_eui2=AeH3vlNkgVjpXi3IK79E5VGP6CLE6ZJpCFToIsTpkmkIVOeNxnm_F_D_6h-cSRo_34zH9ydb0sYkjVRMJh47rqU7&_nc_ohc=waea-Lhy868AX9fm1fx&_nc_oc=AQn5q0xcsbu9Y1cyZSMbHPL3IX5N1AJ9OfwcC-ZROAcPIDq5TIb86ypquLdn-d8qJpYociCoEHFu76krcPhxnwyA&_nc_ht=scontent.fbkk5-3.fna&_nc_e2o=s&oh=00_AfBqCTmBKI8jfEw0XV1jrwClftvq-LO_woFp-64lyG3BTA&oe=6521BB18",
    skills: [
      "Python",
      "SQL",
      "Data Engineering",
      "AI",
      "ML", 
    ],
  },
  {
    username: "user15",
    name: "Ahnaf Hasan Shifat",
    city: "Chittagong",
    course: "BSc",
    work: "Frontend Developer",
    msgURL: "",
    linkedinURL: "https://www.linkedin.com/in/ahnafhasan144",
    imageUrl: "https://avatars.githubusercontent.com/u/81911439?v=4",
    skills: [
      "Front End Development",
      "HTML",
      "CSS",
      "JavaScript",
      "C",
      "C++",
      "NodeJS",
      "ReactJS",
      "Postgresql",
      "TailwindCSS",
    ],
  },
  {
    username: "user16",
    name: "vczoika",
    city: "Sao Paulo",
    course: "CC",
    work: "Backend Developer",
    msgURL: "",
    linkedinURL: "https://www.linkedin.com/in/vini-sales",
    imageUrl: "https://avatars.githubusercontent.com/u/26311011?v=4",
    skills: [
      "Front End Development",
      "C",
      "Java",
      "Rust",
      "SQL and NoSQL",
      "OS",
    ],
  },
  {
    username: "user17",
    name: "Hrisikesh Roy",
    city: "Dhaka",
    course: "BSc",
    work: "Backend Developer",
    msgURL: "",
    linkedinURL: "https://www.linkedin.com/in/hijal/",
    imageUrl: "https://avatars.githubusercontent.com/u/21256564?v=4",
    skills: [
      "HTML",
      "CSS",
      "JavaScript",
      "C",
      "C++",
      "NodeJS",
      "ExpressJS",
      "Restify",
      "ReactJS",
      "Vuejs",
      "PostgreSQL",
      "MySQL",
      "Docker"
    ],
  },
  {
    username: "user18",
    name: "Mahendra Kumar",
    city: "Jaipur",
    course: "MCA",
    work: "Fullstack Developer",
    msgURL: "solankirakesh895@gmail.com",
    linkedinURL: "https://www.linkedin.com/in/mahendrakumar99/",
    imageUrl:
      "https://shorturl.at/dyR15",
    skills: [
      "Frontend",
      "Backend",
      "Database",
      "Javascript",
      "React",
      "NodeJs",
      "ExpressJS",
      "MongoDB",
      "Tailwind",
      "Sass",
      "Java"
    ],
  },
  {
    username: "user19",
    name: "Mohammad Mursaleen",
    city: "Mau",
    course: "MCA",
    work: "Fullstack Developer",
    msgURL: "mmursaleenstb18@gmail.com",
    linkedinURL: "https://www.linkedin.com/in/mohammad-mursaleen-9b8223228/",
    imageUrl:
      "https://media.licdn.com/dms/image/v2/D5603AQE9RKqFEyq0fA/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1706026745948?e=1729123200&v=beta&t=etoEhsbLEMd7_kSi7c1vGgPIn0TsEqtFZqk5PuefqFM",
    skills: [
      "Frontend",
      "Backend",
      "Database",
      "Javascript",
      "React",
      "NodeJs",
      "ExpressJS",
      "MongoDB",
      "Tailwind",
      "Sass",
      "Java"
    ],
  },
  // Add your Data order wise
];

export default userProfiles;
